k3s_channel: stable
k3s_server_group: k3s_servers
k3s_primary_server: "{{ groups[k3s_server_group] | first }}"
k3s_server_url: "https://{{ hostvars[k3s_primary_server].ansible_host | default(k3s_primary_server) }}:6443"
k3s_server_config:
  cluster-init: true
  disable:
    - traefik
    - servicelb
k3s_agent_config: {}
k3s_registries_config:
  mirrors:
    "192.168.1.243:5000":
      endpoint:
        - "http://192.168.1.243:5000"
    "registry.home.arpa:5000":
      endpoint:
        - "http://registry.home.arpa:5000"
k3s_update_system: true
k3s_kubeconfig_dir: "{{ playbook_dir }}/../kubeconfig"
k3s_kubeconfig_name: aetherion.yaml
