apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - monitoring-grafana-admin.sealedsecret.yaml
  - grafana-dashboard-k3s-cluster-overview.yaml
  - grafana-dashboard-spend-app-overview.yaml
