apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: monitoring-grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCTMdNmzlXDnYH47P5aQnHytZLFydpPxU3vQzKTsJj6srKnbXlsCx8cyojVFhvTIUXkkl87bQOxKtYL43TQLW/IYaPEPM8XFPVUAroUIfBAqtQ0fOW9cknfH1GxySuOLBIu+up70geoSKNUaB8ij5ARxjHNcJB726GPDeamUh6oGUdCGteAWvsUG/IEnZmJkJ71CDfOBYkjZbdGw9WOmk3o/23/ZyhtKFxmxRkcCPGTedZ6WSZSALmnpzOnBhoYbwCplVxBXXMCPqxQnv52K8n3zLI6sjL0ukUaDGMzfqth3EyoNfFEJHIptoCcODPmWb/5BayonOCT2N/7c2OKyXPAps2JYkFxQa6Sqa5QBUyDwEEnAYpCxbdf+mkDe5g1FewN4QsybqIYC/xywTCHl+vfJ97ny3ttnPnbCV9GxZ4xEjpTqdK8cF46VOb+N37KagHZdzql2G4gO6L3vmXtX5SlVWpff8t+XHDpgyY5WpI5wwO3JmblsP3Mc7p0d2wnnvwemk5D9vda1leBD9hQuVDs8l7iZlwVRmlDANRAk6D/RfndzLEuQ5rGWwdu5MCkWRRUqvW5qKDpeM6jPZIpWVq4q8uFPRGjCMGW9rgPhs1gQLEUzj9dZZKtJYUM50EM4VyozFUSP6zFY2F9SzPH5cvSi3YZxzr5x8cJzEzEvXTZ0wPazCwGNJl+k3zaXVlHAdKHi/kFBJm1S34=
    admin-user: AgAzkATDePmJSut5FnN3IF15Cm7J3Wg5BuUb2t+oTX9aMxlXQEo5XIiLG0a02ZrXRDaQvdmMRj43SrkS4h3SRlzY4YWJ0zMCsg4p90otajjBH62EKnjNDeDJs+M+lSbbpBWt9b7DjoD2gyIs+zY7vDgIoq6VMNTg4Oa5oivbGT4VQAjNCphy4pXuHy/wTpwnnx/9QX9yd4Ba8B18TQRHYpNCphl/90iX4oNmx+qR7fdrC7bjfkBt6Vvnm96eiQ4mbqHvt+TGJg/vjLv6z1Ip+BW0lOgUADoQc5+AW2b4T2hcTxcPjhSjkJsWFPM5RLxLe+GQqfgdWlzm7Q5zbHitK9I1ikv67Zp2XCqeO97hMjqQZlACeXH8Jz7HUzo2OyjqPM1DNFZ18Ym8vYarDHNdgPA7N7q/ixSBFjrDn/iGRYcb60nZMkoMLvjpGUB/xhsNcpdbZO5qQwlT+d7KtI7QXO4P8qidQOutj9fDmte+kJEDFTvcHm/T8X68XBoHTSLDlnKMuEdOMDcL2riC7JPuqvYQdhMFYfSRl5qRJth/yPqdOFXoT06RvY2wW7FaHrSQ9DzyvhX44pEYJkiAT+bxLvrK/AQCcJXNi+GE+VYhBBTjeefoNvO8XK9s14wnZ6MvUkSJMOTSDhPab1DvyovG6jfvoD3PcOIpgUYtAZPz3CjOqV9eYvSqN1ijSGDq2Kz/5Mla4DX4Bw==
  template:
    metadata:
      name: monitoring-grafana-admin
      namespace: monitoring
    type: Opaque
