apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 9.5.13
      helm:
        releaseName: argocd
        valueFiles:
          - $values/helm/platform/argocd/values.yaml
    - repoURL: http://gitea.gitea.svc.cluster.local:3000/sergiocltn/k3s.git
      targetRevision: main
      ref: values
    - repoURL: http://gitea.gitea.svc.cluster.local:3000/sergiocltn/k3s.git
      targetRevision: main
      path: helm/platform/argocd/app
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
