apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 85.0.2
      helm:
        releaseName: monitoring
        valueFiles:
          - $values/helm/platform/monitoring/values.yaml
    - repoURL: http://gitea.gitea.svc.cluster.local:3000/sergiocltn/k3s.git
      targetRevision: main
      ref: values
    - repoURL: http://gitea.gitea.svc.cluster.local:3000/sergiocltn/k3s.git
      targetRevision: main
      path: helm/platform/monitoring/app
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
