apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: external-dns-pihole
  namespace: external-dns
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgApIflFRi7qgPdBLXOTPvDqxLHqKzzgUz6GZlfZ38O73EsBh5PcipICtHaxtVyiCKLwd0YNR7niWMGbhuwv7SuX8VcC/Rf3BgOnlWz9bqfMudP9DgpVshuy9qF+8OiMWaugqms/tf9YjiT+JE92GOBU5G2u3TMaKV7w1KK+1LnkFCnuKCn6XdeYp97QTsrOUIHPVxZfFYQf17tnhy2aANk6QJQHpHfNVt9nFqGfpI+5gDO+Bua2St8pbR1KvNxfqYys6pumpsLOc3gSzzS3TRSCv+jwFLoNkW8dIFo7TSVJD4TJCCYcUQDbrEQ5QY/LsxFEw365U3MoBrUMIZLm4mtjLoQlEqi0BHG7udLYxJZcEerQk5VcfMNMdZa356Dm9mFyuYOZ8wyOMULfGQfq3AeD/SFtyxljFEDLaBNi1LAsrZgGAKKWmsDY7KXw+dVBxAtfTjwFH8dJ4UV40XRf7Jh97VSvgwrYIiXKCl/gNoLaMWn0wb5um1kbNLe/GPUnrZoZrBmpClFuNPJ1g5zzCdnKgMcU3sQEiY+Kt5AvDK1wluqb+OSQ/j5n8+lurVdmy6ww0uqP+JlLefInK+7qobYtDCT4qGei1rZVQEtHCvBQqnbreL7Er34UDh2h9SRdB3IS4MrNi3XlcDSxXMF1Uy64zsL0L5Et3FpYL1cKsMWAF05OKld9ZPO5aEQ5iicRkI1w9tUC0lCNJI5N+6GguG6HuCmS0/yMWSNEt9sLgEZviTqOz4p51u2amnM3DANLCVY=
  template:
    metadata:
      name: external-dns-pihole
      namespace: external-dns
    type: Opaque
