apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pi-hole-data
  namespace: pi-hole
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-hole
  namespace: pi-hole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pi-hole
  template:
    metadata:
      labels:
        app: pi-hole
    spec:
      containers:
        - name: pi-hole
          image: pihole/pihole:latest
          env:
            - name: TZ
              value: Europe/Madrid
            - name: FTLCONF_dns_listeningMode
              value: ALL
          envFrom:
            - secretRef:
                name: pi-hole-web
          ports:
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /etc/pihole
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pi-hole-data
---
apiVersion: v1
kind: Service
metadata:
  name: pi-hole
  namespace: pi-hole
spec:
  type: LoadBalancer
  selector:
    app: pi-hole
  ports:
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
