apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pi-hole-web
  namespace: pi-hole
spec:
  encryptedData:
    FTLCONF_webserver_api_password: AgBf6RdE5EUL+uDeYzZHfQWNSlWVdCn0ChdlXWk+Lx18Ty9K/DDCqNRXS0NPwTPOZ0d0VOsuxjGPR+ZuIsx86+45nLIcxARMa1/ls8McGn9o7aZWNlyTdDS2FdjC+SzCr+m40fr+JmSUAYDLN0CI43K95QEymqBffU04yCi0zT7/3rrTtAPpL68LoeCgddEsH1l2m+f0NMW33n8GBItqvshYAg7an/nhqjCnU5bpDkE0JuVmunGbxBweJ8KATgeMgYlfe/Ah3mD8/ZYt1r50q5y8zqO5leVgBYmUq1AsDpsI1mdXwBUUQhsXqohSaBhdJqVjNs1oLPE6/+8wYH3wUoGnD3q1KLHiJYLR2GQB9Uk05R0dGKmwzYNYkkOy4sGhduBxLdB7Je/+jYfqqNcaO69zmh+s3126YQEY3asqtsrZdjBam7qsUfP2/xlcc3TrOflZNuVR7ZGEiiIuJFU6noCcfgE9jGSvFSFY+pMxLt/kLorkr//n/h5ZAnQWnUnC597IB/YRMbrdubipmISQKAiyJFUveTBG2nPRZUYYkobrE88bS+26Eo2QWO9D4Ue9K4tfp+UyIgYiI1G4TO/gHZhZDxse/2KIMKEEutIV+YK/MHvBWvZ12amhJuQd7lt6oV0uH2Yd6FpHVDONkQLMvTkkNPuyI0ww6dbMHrPpppOCSvcKXd9PeYw+f/59Sn4/cgsN+ZO0R++e3QExbs3g2HUDcGNkgibxtr0BV7Ajg+E+wumm7hWksBzu3SFHgT4thBg=
  template:
    metadata:
      name: pi-hole-web
      namespace: pi-hole
    type: Opaque
