apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trading-bot
resources:
  - namespace.yaml
  - trading-bot-env.sealedsecret.yaml
  - pvc.yaml
  - warmup-job.yaml
  - cronjob-donchian.yaml
  - cronjob-tsmom.yaml
