apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://gitea.gitea.svc.cluster.local:3000/sergiocltn/k3s.git
    targetRevision: main
    path: helm/apps/registry
  destination:
    server: https://kubernetes.default.svc
    namespace: registry
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
