controller:
  config:
    use-forwarded-headers: "true"
  ingressClassResource:
    name: nginx
    enabled: true
    default: true
  ingressClass: nginx
  watchIngressWithoutClass: false
  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
    ports:
      ssh: 22
    targetPorts:
      ssh: 22
tcp:
  22: "gitea/gitea:2222"
